Exploratory Data Analysis - Airline Delay Causes
========================================================

```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(ggthemes)
library(data.table)
library(GGally)
```

```{r message=FALSE, warning=FALSE}
data <- read.csv("../data/airline_delay_causes.csv")
str(data)
nrow(data)
```

## Transform delay counts into categorical variable

```{r message=FALSE, warning=FALSE}
data.delay <- data[which(data$arr_del15 >0 ), ]
data.delay$season[data.delay$month%in% c(12,1,2)] <- "Winter"
data.delay$season[data.delay$month%in% c(3,4,5)] <- "Spring"
data.delay$season[data.delay$month%in% c(6,7,8)] <- "Summer"
data.delay$season[data.delay$month%in% c(9,10,11)] <- "Fall"


nrow(data.delay)
```


```{r message=FALSE, warning=FALSE}

dt <- data.table(data.delay)

dt.total <- dt[, list(tot_carrier_ct= sum(carrier_ct), tot_weather_ct=sum(weather_ct), tot_nas_ct = sum(nas_ct), tot_sec_ct = sum(security_ct),tot_late_aircraft_ct = sum(late_aircraft_ct))]

dt.total <- dt.total[, list(delay_var = names(.SD), count = unlist(.SD, use.names = F))]

df.total <- as.data.frame(dt.total)
df.total$delay_category[df.total$delay_var == "tot_carrier_ct" ] <- "Carrier Delay"
df.total$delay_category[df.total$delay_var == "tot_weather_ct" ] <- "Weather Delay"
df.total$delay_category[df.total$delay_var == "tot_nas_ct" ] <- "NAS Delay"
df.total$delay_category[df.total$delay_var ==  "tot_sec_ct" ] <- "Security Delay"
df.total$delay_category[df.total$delay_var == "tot_late_aircraft_ct" ] <- "Late Aircraft Delay"
```


### Analysis of the delay causes on the airline delays

```{r message=FALSE, warning=FALSE}
delay.causes <- ggplot(df.total, aes(x = reorder(delay_category, count), 
    y = count)) + theme_few() + scale_colour_few()
delay.causes <- delay.causes + geom_bar(stat = "identity") + coord_flip()
delay.causes <- delay.causes + ggtitle("United States\nDelay Cause  Impact on the Airline On-Time Arrival\n2004 - March. 2014") + 
    ylab("Total Delay Count") + xlab("Delay Category")

delay.causes
```

### Top 10 Airlines with most percentage of flight delays
```{r message=FALSE, warning=FALSE}
df.top10airlines <- dt[, list(perc_delay_air= sum(arr_del15)/sum(arr_flights)), by=carrier]

df.top10airlines <- df.top10airlines[,rank:=order(-rank(perc_delay_air), carrier)]

df.top10airlines <- df.top10airlines[rank <=10]

top10.airlines_delay <- ggplot(df.top10airlines, aes(x = reorder(carrier,-perc_delay_air), 
    y = perc_delay_air)) + theme_few() + scale_colour_few()
top10.airlines_delay <- top10.airlines_delay + geom_bar(stat = "identity")
top10.airlines_delay <- top10.airlines_delay + ggtitle("United States\nTop 10 Airlines by Percentage of Delay Share\n2004 - March. 2014") + 
    ylab("Percentage of Flights Delayed, %") + xlab("Airline Carrier")

top10.airlines_delay

```

### Top 10 Airports with most percentage of flight delays
```{r message=FALSE, warning=FALSE}
df.top10airports <- dt[, list(perc_delay_air= sum(arr_del15)/sum(arr_flights)), by=airport]
df.top10airports <- df.top10airports[,rank:=order(-rank(perc_delay_air), airport)]
df.top10airports <- df.top10airports[rank <=10]

df.top10airports_delay <- ggplot(df.top10airports, aes(x = reorder(airport,-perc_delay_air), 
    y = perc_delay_air)) + theme_few() + scale_colour_few()
df.top10airports_delay <- df.top10airports_delay + geom_bar(stat = "identity")
df.top10airports_delay <- df.top10airports_delay + ggtitle("United States\nTop 10 Airports by Percentage of Delay Share\n2004 - March. 2014") + 
    ylab("Percentage of Flights Delayed, %") + xlab("Airport")

df.top10airports_delay

```

```{r message=FALSE, warning=FALSE}
dt.pairs <- dt[, list(delay_count = arr_del15, arr_delay_min = arr_delay, carrier_ct,weather_ct, nas_ct, security_ct, late_aircraft_ct)]

df.pairs <- as.data.frame(dt.pairs)

ggpairs(df.pairs, 
     upper = list(params = c(size = 10)),
    lower = list(continuous = "smooth", params = c(method = "loess", fill = "blue")), legends=TRUE,
    title = "Correlation Plot") 

```

